version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-tier

  vote:
    image: varyagus/examplevotingapp_vote:v1
    container_name: vote
    # build: ../vote/
    ports: 
      - "5000:80"
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    image: varyagus\examplevotingapp_result:v1
    container_name: result
    # build: .
    ports:
      - "5001:80"
      - "5858:5858"
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: varyagus\examplevotingapp_worker:v1
    container_name: worker
    # build: ../worker/
    depends_on:
      - redis
      - db
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
